apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: njdycwzud-java-springboot
  janus-idp.io/tekton: njdycwzud-java-springboot
  backstage.io/kubernetes-id: njdycwzud-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: njdycwzud-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
